concord-consortium/cloud-file-manager

src/assets/examples/hide-hamburger.html, src/assets/examples/index.html, src/code/views/dropdown-view.coffee
This is for part of [this story](https://www.pivotaltracker.com/story/show/110292104)
For optionally hiding the CFM menu dropdown when embedded in CODAP (in LARA)
[#110292104]
=> Hide the hamburger dropdown when no menu specified in opts.

src/code/client.coffee
I ran into this on the train with four or five auto-save requests pending simultaneously.
=> Disable auto-save when a save is pending

src/assets/examples/menu-madness.html, src/code/client.coffee, src/code/providers/google-drive-provider.coffee, src/code/providers/provider-interface.coffee, src/code/ui.coffee, src/code/utils/lang/en-us.coffee, src/code/views/alert-dialog-view.coffee, src/code/views/app-view.coffee, src/code/views/file-dialog-tab-view.coffee, src/code/views/local-file-tab-view.coffee, src/code/views/modal-dialog-view.coffee, src/code/views/modal-view.coffee, src/code/views/share-dialog-view.coffee, src/style/components/alert-dialog.styl, src/style/components/modal.styl
Adds an alert dialog that can be overlayed on existing dialogs if need be.  A zIndex property was added to the modal view to accomplish this overlay.
=> Changed browser alerts to centered alert dialogs [#114585515]

src/assets/examples/enable-demo-extension.html, src/assets/examples/enable-lara-sharing.html, src/assets/examples/index.html, src/code/client.coffee, src/code/providers/document-store-provider.coffee, src/code/providers/google-drive-provider.coffee, src/code/providers/localstorage-provider.coffee, src/code/providers/provider-interface.coffee, src/code/providers/readonly-provider.coffee, src/code/ui.coffee, src/code/utils/lang/en-us.coffee, src/code/views/app-view.coffee, src/code/views/blocking-modal-view.coffee, src/code/views/confirm-dialog-view.coffee, src/code/views/download-dialog-view.coffee, src/code/views/file-dialog-tab-view.coffee, src/code/views/import-tabbed-dialog-view.coffee, src/code/views/local-file-tab-view.coffee, src/code/views/share-dialog-view.coffee, src/code/views/url-tab-view.coffee, src/style/components/alert-dialog.styl, src/style/components/confirm-dialog.styl, src/style/components/file-dialog.styl, src/style/components/menu-bar.styl, src/style/components/modal.styl, src/style/components/share-dialog.styl, src/style/components/tabbed-panel.styl, src/style/mixins/fonts.styl
All the PT story numbers refer to the CODAP project.
=> CODAP integration features and bug fixes

src/code/providers/document-store-provider.coffee
The auth component is now shown instead of an empty list.
=> Fixed session timeouts in document store.   [#108448644]

gulp/config.js, package.json, src/code/app.coffee, src/code/client.coffee, src/code/globals.coffee, src/code/providers/document-store-provider.coffee, src/code/utils/lang/en-us.coffee, src/code/views/download-dialog-view.coffee, src/code/views/dropdown-view.coffee, src/code/views/file-dialog-tab-view.coffee, src/code/views/menu-bar-view.coffee, src/code/views/rename-dialog-view.coffee, src/code/views/share-dialog-view.coffee, src/code/views/tabbed-panel-view.coffee, src/code/views/url-tab-view.coffee
- better detection/handling of expired/stale credentials [#116484877]
- automatically bring up login dialog when possible/appropriate
- dismiss login dialog appropriately upon success [#116342015]
- clear window.location.hash when appropriate
While we're here also, update some dependencies (including React 15.0.1) and add convenience scripts to the package.json.
=> Improved handling of doc store authorization errors

src/code/providers/document-store-provider.coffee, src/code/utils/lang/en-us.coffee, src/code/views/alert-dialog-view.coffee
- Add inline styling to override CODAP styling
- Change alert dialog to use raw html like confirm dialog
- Don't show save deprecation warning dialog when launched from Lara
=> Fix deprecation dialog

src/code/providers/lara-provider.coffee
Use full URL for reporting_url [#131441319]
=> Use full URL for reporting_url

src/code/views/file-dialog-tab-view.coffee
Fixes crash Evangeline discovered
=> Add null test in getSaveMetadata()

package.json, src/code/client.coffee, src/code/views/local-file-tab-save-view.coffee
One more extension to support saving exported graph pictures as local files
=> Support saving exported picture as local file

src/code/providers/lara-provider.coffee
If patch save fails, try a full save before reporting error to user [#130829875]
Note: I started this initially as a means of giving Evangeline an alternative build to test while investigating https://www.pivotaltracker.com/story/show/131313927. It can be merged (or not) at whatever point makes sense relative to that more important issue.
=> If patch save fails, try a full save before reporting error to user

src/code/client.coffee, src/code/providers/document-store-provider.coffee, src/code/providers/google-drive-provider.coffee, src/code/providers/lara-provider.coffee, src/code/providers/local-file-provider.coffee, src/code/providers/localstorage-provider.coffee, src/code/providers/readonly-provider.coffee, src/code/providers/url-provider.coffee, src/code/ui.coffee, src/code/views/provider-tabbed-dialog-view.coffee
Files opened from Local can now be saved to Google Drive [#134090113]
- replace 'forceSaveDialog' metadata property with 'resave' provider capability
- rename 'saveUnwrapped' provider capability to 'export'
- update capability specifications for all providers
Fix handling of client-provided submenus
=> Fix save local file to google drive

src/code/client.coffee
Once more unto the breach...
With the changes in PR#65, some code paths resulted in the presentation of multiple save dialogs. This occurred because in `CloudFileManagerClient` the `saveFileDialog()` and `saveFileAsDialog()` methods call `_dialogSave()` once the dialog is dismissed. The `_dialogSave()` method calls `saveFile()`, which optionally brings up the save dialog. The changes in PR#65 triggered this latent issue. The fix here is to pull out the actual saving code from `saveFile()` into a `saveFileNoDialog()` method. With this change, `saveFile()` calls `saveFileDialog()` or `saveFileNoDialog()` as appropriate, and `_dialogSave()` calls `saveFileNoDialog()`, thus eliminating the potential for redundant dialogs.
=> Prevent redundant save dialogs

src/code/client.coffee, src/code/providers/document-store-share-provider.coffee
NOTE: this is a noop until this docstore PR is merged and deployed:  https://github.com/concord-consortium/document-store/pull/21
=> Added docstore call when removing sharing [#130691121]

src/code/providers/document-store-provider.coffee, src/code/utils/lang/en-us.coffee
* All strings are now localized
* The permissions error was reworded to make it more user friendly
=> Updated docstore provider alert messages [#130691121]

src/code/views/local-file-tab-save-view.coffee
Use browser events for the download button rather than React events for predictable behavior [#136287689]
The onClick handler for the download button was getting triggered multiple times and preventDefault seemed not to work as expected. The resulting behavior varied between browsers and sometimes between dev and non-dev builds. After spending too much time trying to fix things in the React SyntheticEvent system, switching to browser event handlers eliminated the oddities.
=> Fix double-download on Local File Save

src/code/client.coffee
Added a postmessage listener that currently consists of two message handlers:
1. getCommands, which returns an array of commands that the postmessage api handles
2. autosave, which autosaves the document if it is able to
=> Added postmessage listener

src/code/views/dropdown-view.coffee, src/code/views/menu-bar-view.coffee
Improves behavior on iPad for filename and dropdown. Also marginally improves behavior on desktop for dropdown.
=> Dropdown filename event handling

package.json
Build was failing.
* require-dir version did not work with node 8
* CODAP build path has moved
=> Fix npm package dependencies and adjust codap build path target

src/assets/examples/client-logging-provider.html, src/assets/examples/index.html, src/code/client.coffee
Makes it possible to create a derived class of `ProviderInterface` and have it added to the list of providers via configuration.
=> Support client-created providers [#152129132]

src/code/client.coffee
Event sent before requesting document content.
Needed in CODAP to display splash screen at the
beginning of a wait, rather than in the middle.
=> [#154456146] Add willOpenFile event to CFM Client

src/code/views/dropdown-view.coffee
Fix submenu behavior on touch systems [#158700996]
- "Once more unto the breach!"
- This was ostensibly fixed by an earlier PR (#106), but a late cleanup/refactoring broke it again.
- On the plus side, this fix is better than the previous one.
=> Fix submenu behavior on touch systems (again)

src/code/views/dropdown-view.coffee, src/style/components/dropdown-menu.styl, src/style/components/menu-bar.styl
https://www.pivotaltracker.com/story/show/162021179
New style:
=> Update style of the hamburger menu, make it more obvious

src/code/app.coffee, src/code/client.coffee
=> Fix postMessage call (Safari was complaining about lack of second argument)

src/code/providers/google-drive-provider.coffee
Google broke CORS on content.googleapis.com so this fix fallback to www.googleapis.com on an error.  It still tried content.googleapis.com first in case this is fixed on Google's side.
=> Added fallback on download error that changes downloadUrl domain

src/assets/examples/index.html, src/assets/examples/show-close-confirm.html, src/code/client.coffee, src/code/utils/translate.coffee, src/style/components/menu-bar.styl
Preparation for upcoming React update (#148) which will also need to be merged to the CODAP branch.
- @dougmartin Does it look like I retained the `master` branch changes?
- @jsandoe Does it look like I retained the `CODAP` specializations? Is there anything here that shouldn't be merged to the CODAP branch?
Ideally, we would turn the remaining `CODAP` branch specializations into configurations so that the CODAP build could be built off the `master` branch. Some efforts have been made along these lines (cf. #110 and [CODAP #241](https://github.com/concord-consortium/codap/pull/241)) but things have no doubt diverged further since then.
=> Merge master branch changes to CODAP branch

.eslintrc, .travis.yml, jest.config.js, package-lock.json, package.json, src/code/client.js, src/code/client.test.ts, src/code/globals.js, src/code/providers/google-drive-provider.js, src/code/providers/provider-interface.ts, tsconfig.json, webpack.config.js
Adding testing framework before I continue with typing and cleanup.
@eireland I added jest here, but there is another fix in this PR that might help us with some of the cypress errors we saw.
=> Add jest testing and linting before travis deploy

src/code/utils/lang/en-US-master.json, src/code/utils/lang/en-US.json, src/code/views/icons/spin.tsx, src/code/views/share-dialog-view.js, src/code/views/share-loading-view.tsx
* Add a 'please wait' message when creating a S3 shared document (it takes longer than the previous method)
[#172324177]
[#172302663]
https://www.pivotaltracker.com/story/show/172302663
=> Add 'please wait' to share.

src/code/utils/lang/en-US-master.json, src/code/utils/lang/en-US.json, src/code/utils/s3-share-provider-token-service-helper.ts
https://www.pivotaltracker.com/story/show/173734184
I've modified interfaces/options, so it's easier to ensure that message in the dialog matches reality.
=> Add information about caching to Shared File Update dialog

jest.config.js, src/code/autolaunch/autolaunch.js, src/code/autolaunch/autolaunch.test.js
=> Autolaunch page: fix params passed to CODAP, rm documentServer, provide cfmBaseUrl only when necessary

src/code/providers/readonly-provider.js
The goal of this and the other PRs tagged with `[CODAP-sync]` is to attempt to eliminate the differences between the CODAP and master branches. Each PR represents a set of changes that were made on the CODAP branch that seem as though they should be sufficiently general that they can be merged to master and made accessible to all clients. Thus, review should consist of two components:
1. From the CODAP perspective, do the proposed code changes accurately reflect the prior behavior of the CODAP branch?
2. From the non-CODAP perspective, do the proposed code changes make sense as the default behavior for non-CODAP clients as well as for CODAP clients? @ddamelin 
---
Modify readonly-provider to resolve relative urls against config URL. …
=> [CODAP-sync] Readonly-provider supports relative urls

src/code/providers/s3-provider.ts, src/code/providers/s3-share-provider.ts, src/code/utils/s3-share-provider-token-service-helper.ts
[#174012764]
This PR implements stop sharing link / feature. I've also tried to simplify `utils/s3-share-provider-token-service-helper.ts` that were copied directly from token-service example app and included unnecessary logic related to firebaseJwt.
=> Implement stop share in S3ShareProvider

src/code/autolaunch/autolaunch.js
=> Fix autolaunch issue (cfmBaseUrl)

package-lock.json, package.json, src/code/client.test.ts, src/code/client.ts, src/code/providers/interactive-api-provider.test.ts, src/code/providers/interactive-api-provider.ts, src/code/ui.ts, src/code/utils/lang/de.json, src/code/utils/lang/el.json, src/code/utils/lang/en-US-master.json, src/code/utils/lang/en-US.json, src/code/utils/lang/es.json, src/code/utils/lang/he.json, src/code/utils/lang/ja.json, src/code/utils/lang/nb.json, src/code/utils/lang/nn.json, src/code/utils/lang/th.json, src/code/utils/lang/tr.json, src/code/utils/lang/zh-Hans.json, src/code/utils/lang/zh-TW.json, src/code/views/app-view.tsx, src/code/views/modal-dialog-view.test.tsx, src/code/views/modal-dialog-view.tsx, src/code/views/select-interactive-state-dialog-view.tsx, src/style/components/select-interactive-state-dialog.styl
Remaining work:
- Uncomment "touch" setInteractiveState with AP supports it (follow on PR)
=> Support Edge case Linked Interactive logic and UI [#179625030]

package-lock.json, package.json
=> Version 1.5.1

package-lock.json, package.json
- Fixed CODAP Build to adjust for icon font path changes
=> Version 1.5.3

src/code/views/share-dialog-tabs-view.tsx, src/code/views/share-dialog-view.tsx
This uses the production full-screen question interactive to enable full screen support.
=> Enabled scaling checkbox for interactive api [#181177779]

src/code/views/file-dialog-tab-view.ts, src/style/components/tabbed-panel.styl
This filters the open and save dialog lists as the user types.
=> Add file list dialog filtering [#183367471]

src/code/providers/google-drive-provider.ts
The file api call returns a token if there are more results than can fit in the returned results.  This change keeps looping until there are no more results.
=> Add loop to Google file listing to get all files [#166448174]

src/code/utils/lang/de.json, src/code/utils/lang/el.json, src/code/utils/lang/en-US.json, src/code/utils/lang/es.json, src/code/utils/lang/fa.json, src/code/utils/lang/he.json, src/code/utils/lang/ja.json, src/code/utils/lang/nb.json, src/code/utils/lang/nn.json, src/code/utils/lang/pt-BR.json, src/code/utils/lang/th.json, src/code/utils/lang/tr.json, src/code/utils/lang/zh-Hans.json, src/code/utils/lang/zh-TW.json
This was missed when the upgrade to the new Google auth flow was done.
=> Added missing scopes message to all translations

src/code/views/file-dialog-tab-view.ts
- On save, don't clear the search filter when a folder is selected
- On save, update the search filter when a file is selected
- Fix file lookup when confirming save over existing file
=> Fixed issues with new file filter dialog on saves [#183367471]

src/code/client.ts
Shows an alert to the user with helpful next steps if the copy fails.
=> Add alert when copy fails [#184239674]

src/code/client.ts, src/code/ui.ts, src/code/utils/lang/de.json, src/code/utils/lang/el.json, src/code/utils/lang/en-US-master.json, src/code/utils/lang/en-US.json, src/code/utils/lang/es.json, src/code/utils/lang/fa.json, src/code/utils/lang/he.json, src/code/utils/lang/ja.json, src/code/utils/lang/nb.json, src/code/utils/lang/nn.json, src/code/utils/lang/pt-BR.json, src/code/utils/lang/th.json, src/code/utils/lang/tr.json, src/code/utils/lang/zh-Hans.json, src/code/utils/lang/zh-TW.json, src/code/views/app-view.tsx
This ensures when a network error resolves itself autosave continues to run.
=> Added back autosave on save failures [#183842099]

src/code/views/file-dialog-tab-view.ts, src/style/components/tabbed-panel.styl
This also fixes a css color issue on the clear "icon" so that it is visible in CODAP.
=> Fixed missing "Loading..." message [#184485531]

src/code/providers/legacy-google-drive-provider.test.ts, src/code/providers/legacy-google-drive-provider.ts
Copied the existing GoogleDriveProvider code and test in order to keep a working copy to compare against while the GoogleDriveProvider is updated to use the Google Drive picker.
=> Created LegacyGoogleDriveProvider [PT-186571871]

package.json, src/code/client.ts, src/code/ui.ts, src/code/views/app-view.tsx
Jira story: https://concord-consortium.atlassian.net/browse/CODAP-879
This PR adds an `updateMenuBar` function to the cfm client, which allows a client to arbitrarily change the menu bar after initialization.
=> CODAP-879 Add updateMenuBar Function
