concord-consortium/cloud-file-manager

gulp/config.js, gulp/tasks/deploy.js, src/assets/examples/index.html, src/assets/examples/view-no-frame.html, src/code/app.coffee, src/code/providers/document-store-provider.coffee, src/code/ui.coffee, src/code/views/app-view.coffee, src/code/views/modal-view.coffee, src/style/components/file-dialog.styl, src/style/components/tabbed-panel.styl
Support for clients (such as CODAP) that want to embed the CFM and have the menubar UI rendered in an element specified by the client. The new behavior is specified by passing a new property (appOrMenuElemId). Shouldn't affect the behavior of existing use cases.
- Gulp configuration to allow client to specify alternate build destination.
- Add view-no-frame example demonstrating the menubar being rendered in a client-specified element without an iframe.
- Add appOrMenuElemId property to CFM client configuration.
- Menubar UI renders if appOrMenuElemId property. Client app is only rendered if usingIframe is true.
- Modal dialog code shadows the entire viewport.
- Minor CSS tweaks to explicitly specify styles that might otherwise be overridden by client defaults.
=> Support menu UI in a client-specified element without iframe

package.json, src/code/client.coffee, src/code/providers/document-store-provider.coffee, src/code/providers/google-drive-provider.coffee
When saving to the Concord Document Store:
-- compress POST data
-- only send patches if the patches are smaller than the full document would be
On save failure:
-- clear the "Saving..." message
-- disable autosave until next successful manual save (to prevent accumulation of error dialogs)
Use 'type' instead of 'method' in jQuery ajax calls to support older jQuery versions (like the one used by CODAP/SproutCore 1.9).
=> CODAP-inspired save improvements

src/code/providers/localstorage-provider.coffee, src/code/utils/get-hash-param.coffee
Fix a bug in handling filenames with spaces (and other characters) that I noticed with the localStorage provider but that could affect any provider.
-- call decodeURIComponent in getHashParam()
-- minor improvement to error-handling in localStorage provider
The code in getHashParam() is written to loop until there's nothing left to decode. I actually ran into a situation in which two decodes were necessary but that presumably occurred because I resaved a document using a version of CFM that wasn't decoding.
=> Get hash param decode uri component

src/code/providers/document-store-provider.coffee
Besides the efficiency, the Document Server patch API returns an error when sent an empty patch.
=> Skip patch API call if patch is empty

package.json, src/assets/examples/read-only-with-folders.html, src/code/globals.coffee, src/code/providers/provider-interface.coffee, src/code/providers/readonly-provider.coffee, src/code/utils/is-array.coffee, src/code/utils/lang/en-us.coffee, src/code/views/file-dialog-tab-view.coffee, src/style/components/tabbed-panel.styl
Supports loading of remote documents as well as remote directories containing lists of documents, thus allowing arbitrary sample document libraries.
-- expands the JSON format to support the new features while maintaining compatibility with the old JSON format
-- adds a 'description' property for documents, which is presented as a tooltip
-- adds a 'url' property for documents which is used to load remote documents
-- adds a 'label' type which is used to show dividers and other non-selectable items in file lists
-- adds the 'es6-promise' module for use in handling async requests for remote directories
=> Read only provider supports remote documents

src/code/providers/document-store-provider.coffee
-- Eliminates a redundancy introduced in an earlier PR
-- Clears @previouslySavedContent when not in use. (Not technically part of the main purpose of the PR, but a hypothesis I tested while debugging a patch failure that seemed like a good idea.)
=> Eliminate double-JSON.stringify on save/patch

gulp/config.js, gulp/tasks/browserify-task.js, gulp/tasks/css-task.js, package.json
Support CODAP gulp configuration via command-line options rather than as a branch or other less desirable alternative.
--nojQuery flag excludes jQuery for use with clients that already have jQuery installed.
--codap flag adds '.ignore' to the .js filenames to hide them from the SproutCore build system.
--codap flag also excludes most assets except a handful of images, since the others are either already present in CODAP (e.g. fonts) or not used in CODAP (e.g. examples).
--noMap flag isn't CODAP-specific -- it disables inclusion of source maps thus allowing debugging with the browser's JavaScript debugger rather than the CoffeeScript debugger.
Shouldn't affect the behavior of the build unless one of the new options is specified.
=> Add gulp command-line options (--nojQuery and --codap) for CODAP configuration

src/code/providers/document-store-provider.coffee, src/style/components/share-dialog.styl
* default text color to black in share dialog
* add existence test for metadata when handling errors such as failure to save when enabling sharing
* saving for sharing purposes use same compression protocol as simply saving
=> Fix share dialog when used in CODAP/CFM

gulp/tasks/browserify-task.js, package.json
Add sourceURL line in CODAP build to simplify debugging for clients that dynamically load CFM (e.g. CODAP). While in the build system, use the 'extname' option of gulp-rename to simplify file renaming.
@dougmartin Since you reviewed the earlier gulp changes, you may want to take a look at these.
=> Add sourceURL line in CODAP build to simplify debugging

src/code/providers/google-drive-provider.coffee
Oops! In an earlier spate of jQuery 1.6 compatibility changes -- renaming 'method' to 'type' in jQuery ajax calls -- I managed to make the same change in the GoogleDriveProvider, which doesn't use ajax and therefore shouldn't be changed.
=> Fix Google Drive save regression

src/assets/examples/all-providers.html, src/assets/examples/auto-saving.html, src/assets/examples/example-app/index.html, src/assets/examples/index.html, src/assets/examples/menu-madness.html, src/assets/examples/new-does-not-use-new-tab.html, src/assets/examples/no-frame.html, src/assets/examples/real-time-api.html, src/assets/examples/view-no-frame-nowrap.html, src/assets/examples/view-no-frame.html, src/code/client.coffee, src/code/providers/document-store-provider.coffee, src/code/providers/provider-interface.coffee, src/code/ui.coffee, src/code/utils/lang/en-us.coffee, src/code/views/share-dialog-view.coffee
Adds support for clients to opt out of the CFM wrapped file format.
Add callback to 'openedFile' API for client to indicate successful completion of open.
Clients that opt out of the CFM wrapper file format are responsible for combining CFM shared metadata with the content in 'getContent' and unpacking CFM shared metadata from the content in 'openedFile'.
Use protocol-relative URLs for http/https compatibility.
Add example document demonstrating opting out of the CFM wrapped file format.
Made the other examples consistent with the 'openedFile' API changes by calling back to acknowledge success.
Eliminated a number of JSHint warnings in examples.
@dougmartin Since @sfentress is out of town for a while, you're the likely candidate to review this. I already did a side-by-side review with Sam …
=> Support opting out of CFM wrapped file format

src/code/app.coffee, src/code/providers/document-store-provider.coffee, src/code/utils/get-query-param.coffee
This allows student to launch shared documents from LARA and save back to their own copies.
When a student launches using from LARA using a document on the document-server which was shared by an author, they do not have write-access to that file. Instead, LARA also providers them with the runKey associated with that document in the url as a query parameter.
If we save to the same document using that runKey, then the document-server will automatically create a copy for us, allowing us to save our changes to it. It will then pass down the new id for the file we have ownership to, allowing us to save to that new document from then on.
We were already capturing a using the new id, but two changes had to be introduced:
1. Capture the runKey and use it on the first save
2. Don't try to save via …
=> Use run key from LARA when saving as a student

src/code/app.coffee, src/code/client.coffee, src/code/providers/document-store-provider.coffee
- If runKey was passed as URL parameter, pass it to document server when loading or saving the document.
This is necessary to support use cases such as teachers viewing student work.
- Support opening and saving documents without authorization when 'runAsGuest' parameter is specified
- Fix copy/paste errors in some request error handlers
=> Improve runKey handling

src/code/client.coffee, src/code/views/download-dialog-view.coffee, src/code/views/url-tab-view.coffee
These are three small bug fixes.
* Couldn't download large documents. This was because a data uri was used. Converted to use a Blob uri. PT [#121523735]
* The "all changes saved" message was no longer displaying when a save completed. The saved state was being overwritten inadvertently. PT [#117561145]
* Finally a drop of a uri list was not correctly handled.
=> Fix download and upload

src/assets/examples/index.html, src/assets/examples/splash-screen.html, src/code/app.coffee, src/code/client.coffee
This adds a client event, `ready`, which is called
1. After the client has connected, if there is nothing left to do (no file to open)
2. After a file has been opened and the app has called the callback
This can be used by the app to know that we're in a ready state and the user can start interacting with the app (hide splash screen, etc.)
Previously, it was not clear from the app perspective whether a file was going to be loaded by the CFM after the initial `connect` event.
=> Notify when ready

src/assets/examples/all-providers.html, src/assets/examples/read-only-with-folders.html, src/code/client.coffee, src/code/providers/document-store-provider.coffee, src/code/providers/google-drive-provider.coffee, src/code/providers/localstorage-provider.coffee, src/code/providers/provider-interface.coffee, src/code/providers/readonly-provider.coffee
This gives the readOnly provider the capability already found in the other providers, that of modifying the url hash when a file is opened, and loading a file when a url with a file fragment is opened.
This way we can link directly to a static example, using `...#file=examples:some-page`
Additionally, apps can chose what to name the providers in the url hash, and have multiple named providers so the fragment can be   `...#file=demos:some-page`, `...#file=AP-curriculum:some-page` or whatever makes most sense given the language of the project.
=> Allow readonly files to be loaded from url hash

src/code/app.coffee, src/code/client.coffee, src/code/providers/document-store-provider.coffee, src/code/providers/document-store-share-provider.coffee, src/code/providers/document-store-url.coffee
Implement DocumentStoreUrl class
- Move responsibility for knowing/manipulating document store URLs and parameters into its own class
- Support redirecting document store requests via 'documentServer' command line argument
- Fixes [#128108157]
Separate sharing functionality into DocumentStoreShareProvider class
=> Refactor for v2 API

src/code/app.coffee, src/code/client.coffee, src/code/providers/google-drive-provider.coffee, src/code/providers/provider-interface.coffee, src/code/ui.coffee, src/code/views/menu-bar-view.coffee
This adds a new url hash param, `newInFolder={provider}:{folder-id}`, which signals that the app should initialize a blank doc and automatically save it back to the provider, under the correct folder.
This is used by the Google Drive API to allow a user to click on the New button within a folder, and have the file be saved back there. (This also works from the home folder, naturally.)
When the doc is first opened, the filename input at the top is selected and focused, allowing the user to immediately name their document.
=> Let Google Drive create new files in specific folders

src/assets/examples/all-providers.html, src/code/client.coffee, src/code/providers/document-store-provider.coffee, src/code/providers/google-drive-provider.coffee, src/code/providers/localstorage-provider.coffee, src/code/providers/provider-interface.coffee, src/code/views/download-dialog-view.coffee
This improves current extension and mimeType handing by
1. Allowing option arrays of additional extensions/mimeTypes to filter on (which should allow us to re-incorporate the extension option in CODAP, as we can now include legacy formats)
2. Not overwriting existing extensions when we open a readable file from a remote location
3. Adding the main extension to downloaded files, but not duplicating it when it is already there
=> Extensions and mime types

src/code/app.coffee, src/code/client.coffee, src/code/providers/document-store-provider.coffee, src/code/providers/document-store-share-provider.coffee, src/code/providers/provider-interface.coffee, src/code/providers/url-provider.coffee, src/code/utils/lang/en-us.coffee, src/code/views/alert-dialog-view.coffee, src/code/views/app-view.coffee
(Note: Depends on [PR #33](https://github.com/concord-consortium/cloud-file-manager/pull/33))
In further preparation for the V2 API...
Rationalize URL/hash parameter handling
- hash params are (still) handled by the CloudFileManager (app)
- url params are provider-specific, and so their handling is moved to individual providers (mainly the DocumentStoreProvider at this point)
- hash/url param processing is moved from CloudFileManager.clientConnect() to CloudFileManagerClient.processUrlParams() (which is called from CloudFileManager.clientConnect())
- CloudFileManagerClient.processUrlParams() gives providers a chance to handle hash/url params
- DocumentStoreProvider handles additional recordid url parameter eliminating the need for CODAP to translate it for CFM
Error handling improvements …
=> Rationalize url param handling; improve error handling

src/code/providers/provider-interface.coffee
Fix handling of null file names in ProviderInterface.matchesExtension()
Null file names can be created by the Document Store
In the V2 doc store API, file names can be empty or null, as they aren't really used for anything any more. Even though we haven't deployed the V2 API to production, anyone that has been testing the V2 API are liable to have documents with null or empty names in their Concord Cloud accounts. Preexisting code for matching file names to extensions wasn't handling null file names. We add the necessary test to the matchesExtension() function, but there may be other places that requires similar treatment.
Note: for this to take effect in CODAP, the corresponding CODAP [PR#90](https://github.com/concord-consortium/codap/pull/90) must be merged.
=> Fix bug in handling of null file names

src/assets/examples/deprecate-phase-one.html, src/assets/examples/deprecate-phase-three.html, src/assets/examples/deprecate-phase-two.html, src/assets/examples/index.html, src/code/client.coffee, src/code/providers/document-store-provider.coffee, src/code/providers/provider-interface.coffee, src/code/ui.coffee, src/code/utils/lang/en-us.coffee, src/code/views/alert-dialog-view.coffee, src/code/views/app-view.coffee, src/code/views/confirm-dialog-view.coffee, src/code/views/modal-dialog-view.coffee, src/code/views/provider-tabbed-dialog-view.coffee, src/code/views/tabbed-panel-view.coffee
Note: This PR depends on [PR#36](https://github.com/concord-consortium/cloud-file-manager/pull/36). Once that is merged, this PR can be rebased accordingly.
Add deprecation warnings for Concord Cloud when opening a document
- DocumentStoreProvider supports 'deprecationPhase' option
- Providers have an opportunity to put up a dialog when files are opened
- DocumentStoreProvider puts up deprecation alert on file open based on deprecationPhase
- Saving (including auto-save) is enabled in phase 1; all saving is disabled in phase 2
- Partially addresses [#129634575] and [#129634587]
- The first commit does not address the save dialog changes described in those stories
- Enhance ConfirmDialogView component to support configurable title, button labels, and a reject callback.
To test this one …
=> Concord cloud deprecation

src/assets/examples/example-app/index.html, src/code/client.coffee, src/code/providers/google-drive-provider.coffee, src/code/providers/localstorage-provider.coffee, src/code/providers/provider-interface.coffee, src/code/ui.coffee, src/code/utils/lang/en-us.coffee, src/code/views/file-dialog-tab-view.coffee, src/code/views/provider-tabbed-dialog-view.coffee
Allows CFM to save a file to a provider, without affecting the current metadata. Used for exporting .csv files in CODAP.
https://www.pivotaltracker.com/story/show/127512941
=> Save secondary file

src/code/views/file-dialog-tab-view.coffee
When switching providers (e.g. saving a file previously saved to Concord Cloud to Google Drive) the provider-specific data in the metadata must be cleared or it can confuse the new provider.
=> Fix Save As bug detected during Concord Cloud deprecation testing

src/code/providers/google-drive-provider.coffee
This was the only place we were not checking for the error message in the returned results.  This should surface the errors thrown for these two stories:
- https://www.pivotaltracker.com/n/projects/1055240/stories/131230747
- https://www.pivotaltracker.com/n/projects/1055240/stories/131230545
=> Added missing check for error in list for Google Drive provider

src/code/views/file-dialog-tab-view.coffee
Fix crash that occurred when opening a file using the LocalFile provider tab in the open dialog and then saving it
- the FileDialogTab component was calling _.cloneDeep() on the metadata, which contains a pointer back to the provider which is not prepared to be copied (it has a pointer back to the client, etc.)
=> Fix crash opening LocalFile then saving

src/code/views/file-dialog-tab-view.coffee
Previously, 707b1cf0 fixed https://www.pivotaltracker.com/n/projects/1055240/stories/120377399,
allowing us to select a parent folder even if we didn't type a name into the Save As dialog.
Then I committed c650f1e6, to fix https://www.pivotaltracker.com/n/projects/1055240/stories/127762907,
making sure we didn't keep a record of the parent folder when switching to different providers.
However, that fix caused a regression which broke the first one. This fix corrects that.
[#130682993]
=> Fixes setting parent folder on newly-saved docs

src/code/views/file-dialog-tab-view.coffee
This fixes the following three scenarios:
1. Correctly save a file to a subfolder in Drive
2. If you open a read-only file, save it to a subfolder in Drive
3. If you open a file from a subfolder in Drive, you can then open from
another provider without it showing that folder name
This area, as @kswenson has mentioned, has had a lot of churn. The two
main issues are (1) confusion over setting metadata parent and setting
folder state, and (2) all the provider views are initialized at the
same time, not when the user switches between them. This makes sense,
but makes it a little harder to reason correctly about.
=> Another fix for subfolders and switching providers

src/code/providers/document-store-provider.coffee, src/code/utils/lang/en-us.coffee, src/code/views/confirm-dialog-view.coffee
- Update dates in deprecation dialogs [#131815401]
- Add missing phase 3 dialog (can get there with documents opened from URL parameter)
Note: This is easier to test with CODAP PR [PR#94](https://github.com/concord-consortium/codap/pull/94) which adds support for a query param override.
=> Update Concord Cloud deprecation phase dates; add phase 3 dialog

src/code/providers/lara-provider.coffee
Before this fix the leader kept on using the shared document - this fix clones the document so that the shared collaborated document state is maintained
=> Fix switch of collaborator document leaders switching to solo mode

src/code/client.coffee, src/code/providers/document-store-share-provider.coffee, src/code/providers/local-file-provider.coffee, src/code/ui.coffee, src/code/views/local-file-tab-save-view.coffee
- allow Local File provider to be selected in export dialog
- support saving/downloading secondary content
This PR ties together Sam's earlier work to [support CSV export](https://github.com/concord-consortium/codap/pull/91) and Doug's recent work to support [local file saving/downloading](https://github.com/concord-consortium/cloud-file-manager/pull/61) so that it is possible to download/save exported CSVs locally. @dougmartin I embarked on this thinking it might be a quick fix before merging your CFM changes into Sam's outstanding PR. It turned out to be a bit more involved.
=> Support saving secondary files (e.g. CSV) to the Local File provider

src/code/client.coffee, src/code/providers/document-store-provider.coffee, src/code/views/file-dialog-tab-view.coffee
- save triggers save as dialog for saving unshared copy
- fixed bug that could prevent saving to another provider after saving to the local file provider
This was the last bit of document save/restore code still being handled by CODAP. Moving it to the CFM enables a much more complete cleanup of the document save/restore code in CODAP.
=> Support legacy sharing with 'doc' and 'owner' query parameters

src/code/client.coffee
Before this change the shared document would always be untitled.  Now the shared document is named the same as the master document when the shared document is created or updated.
=> Set shared docname from master doc [#134644127]

src/code/providers/lara-provider.coffee
Declare explicit dependency on pako library in LaraProvider [#134879527]
- previously, code was implicitly relying on presence of pako global, which was recently removed
=> Declare explicit dependency on pako library in LaraProvider

src/code/views/menu-bar-view.coffee
CODAP eats the click events in the main workspace which cause the blur event not to be triggered for the filename rename input element.  This adds a global window listener to simulate the blur event.
=> Fixed filename input not closing when user clicks in document [#127301439]

src/code/client.coffee, src/code/lib/file-saver.js, src/code/utils/lang/en-us.coffee, src/code/views/local-file-tab-save-view.coffee, src/style/components/file-dialog.styl
On Safari, behavior is to automatically download the file with name "Unknown". Due to limitations of Safari, this seems to be the best we can do. To accomplish this we introduce the FileSaver.js library (https://github.com/eligrey/FileSaver.js) which attempts to provide the best cross-browser support possible.
If the 'download' attribute is supported, uses the original code to download the file. If the 'download' attribute is not supported (e.g. Safari), uses the FileSaver.js library to perform the download. WebKit Nightly and the Safari Technology Preview both support the 'download' attribute, so the FileSaver.js library will only be necessary for a limited time.
In conjunction with a change to CODAP to allow import of files without extensions, CODAP will be able to open downloaded …
=> Improve Safari Local File save [#135154489]

src/code/views/local-file-tab-list-view.coffee
While testing CFM PR #75 (validate document contents) I encountered the fact that files dropped in the drop zone weren't giving the expected error alert message. This turned out to be because the CODAP document drop handler was handling the 'drop' event before the React onDrop() handler. It had been noticed (but not investigated) previously that dropping a file in this dialog sometimes behaved differently than selecting a file from the file chooser and this is presumably the reason for such discrepancies. The fix is to install a DOM event handler on the element rather than using the React onDrop() mechanism.
=> Fix local file tab drop handling

src/code/providers/lara-provider.coffee
@scytacki did all the hard work:
> When viewing one of these read-only links, when the user makes a change (or if the data interactive triggers a change). Then the error message:
> "Unable to save undefined: [error.missingParam]" is shown.
> 
> In this document the data interactive causes CODAP to try to autosave right away.  This issue was fixed previously in this PR: https://github.com/concord-consortium/cloud-file-manager/pull/58.
> I think it is caused by the change to 'resave' [here](https://github.com/concord-consortium/cloud-file-manager/blob/master/src/code/client.coffee#L339)
> Which wasn't added [here](https://github.com/concord-consortium/cloud-file-manager/blob/master/src/code/providers/lara-provider.coffee#L81)
=> LaraProvider should disable autosave with read-only access key (again)

gulp/config.js, gulp/tasks/browserify-task.js, package.json
- upgrade React to version 15.4.1
- add --noReact option to exclude React/ReactDOM from globals.js
- modify `build:codap` script to specify --noReact option
=> React build improvements

src/code/providers/google-drive-provider.coffee, src/code/utils/lang/en-us.coffee, src/code/views/authorize-mixin.coffee, src/code/views/file-dialog-tab-view.coffee
Eliminate `setState called on unmounted component` React warnings
- use synchronized instance variable and state variable in GoogleDriveProvider and AuthorizeMixin
- added _isMounted instance variable to handle cases in which component is unmounted when asynchronous call returns
I didn't make the corresponding changes in the DocumentStoreProvider, since that's going away imminently.
Note: It's possible that some of the Google Drive authorization-related oddities that have been reported could be affected by authorization state-handling, so some testing of those issues would make sense.
=> Eliminate react warnings

src/code/client.coffee
This support is enabled with the existence of the new saveSecondaryFileViaPostMessage query parameter.
=> Added support to export data via postmessage instead of the Save As file dialog [#138395609]

src/style/components/dropdown-menu.styl, src/style/components/menu-bar.styl
Fixes [#137658223] (from Bill Finzer, who originally made the change locally within CODAP)
Increase padding-right for the menu and decrease padding-left for the file menu
=> Hamburger menu too close to doc name for touch

src/code/providers/google-drive-provider.coffee
Changed the file download to specify the access_token as a query parameter instead of request header.  This avoids a CORS OPTIONS request which fails in IE 11 because the server response for the accept-header from Google is longer than 1024 bytes.
=> Fixed CORs auth server response bug in IE 11 [#149863936]

gulp/config.js
This was causing the the browserify tasks to include sourcemaps in production builds.
=> Fixed missing export of production flag in config

src/code/providers/lara-provider.coffee
Optionally pass LARA information back to client for logging [#151493445]
passes the following information (if known)
- run state URL
- document store document ID
- document store document URL
- collaborator URLs
Note that this relies on the client providing a `logLaraData` callback, which will be added to CODAP in [CODAP PR #202](https://github.com/concord-consortium/codap/pull/202).
=> Optionally pass LARA information back to client for logging

src/code/client.coffee, src/code/providers/post-message-provider.coffee, src/code/providers/provider-interface.coffee
Make it easier for third parties (e.g. Zoom In Science) to work with CFM:
- eliminate hard-coded provider dependencies
- make it possible to avoid user-facing dialogs with appropriate providers
Only instantiate `DocumentStoreShareProvider` when using the `DocumentStoreProvider` [#152333125]
Add `autoProvider` architecture
- providers can support a capability without user intervention (i.e. without dialogs)
- `saveContent()` and `saveSecondaryFileAsDialog()` methods check for `autoProvider` [#152332814]
- move `saveSecondaryFileViaPostMessage` capability into new PostMessageProvider
=> "Headless" CFM

src/code/providers/lara-provider.coffee
Note: I'm not set up to run LARA locally, so I've written this code on spec but haven't had a chance to test it yet. The results won't appear in the CODAP logs until the corresponding [CODAP PR](https://github.com/concord-consortium/codap/pull/210) is merged as well.
=> add `run_remote_endpoint` from interactive run state to `logLaraData` [#151493565]

src/code/client.coffee, src/code/providers/document-store-provider.coffee, src/code/providers/document-store-url.coffee, src/code/providers/lara-provider.coffee
Support `log` callback for logging through client application [#152333085]
- add `save` logging to `DocumentStoreProvider` and `LaraProvider` for debugging purposes
Eliminate trailing slashes from `@docStoreUrl`
- having recently encountered situations in which redundant slashes caused problems for some servers, we proactively remove the potential problem.
@scytacki Does this look like the right information to log to help with debugging the document corruption issue?
=> Support logging callback

src/code/providers/google-drive-provider.coffee
`drive.readonly` gives us permission to read all files, for the file
dialog, and we already have write permissions to the files we create
through the `drive.file` permission.
=> Reduce `drive` permission to `drive.readonly`

src/code/providers/google-drive-provider.coffee
Hi @dougmartin, this is a one-line PR. It tells the CFM that Google Drive always requires authorization, and the existing CFM functionality then kicks in to show the authorization popup before trying to open a file from a url. This is deployed to gh-pages, and demo steps can be seen at the PT story below.
Fixes https://www.pivotaltracker.com/n/projects/1055240/stories/133639103
---
If the user is either
1. not logged into Drive, or
2. has not authorized the app
we will show the authorization dialog.
[#133639103]
=> Authorization is required for Google Drive

.gitignore, src/code/views/share-dialog-view.coffee, src/style/components/share-dialog.styl
Changes:
- switch default page to "autolaunch"
- add "autolaunch" / "launch" page checkbox
- add "fullscreen scaling" checkbox (it passes "scaling" URL param to doc-server, which modifies CODAP iframe to scale down and include fullscreen button)
- display inputs bases on page tyle (Launch Button Text for "launch" page, scaling for "autolaunch")
- cleanup and simplify some related code (e.g. `lara` state was redundant, it can be generated using other properties; simplify some event handlers, remove refs)
Screenshots:
@dougmartin or @kswenson, could you take a look? @dougmartin seems to be the main contributor, but @kswenson works on IS2 project. 😉
=> Update LARA share dialog to use autolaunch page and fullscreen scaling

src/code/views/share-dialog-view.coffee
It got broken as I removed `lara` from the state. I'm betting `embed` and `link` could also be removed in the future if they can be calculated at any time (it seems so). Keeping them in the state is redundant.
[#156243160]
=> Fix copy link in LARA share dialog

src/code/views/file-dialog-tab-view.coffee
We were suppressing directory list if dialog not mounted, but this
check failed for localStorage because directory is loaded
synchronously. To fix moved setting of isMounted to init method, since we only care when it gets set to false.
=> Fix ability of local storage provider to list directory

src/code/views/dropdown-view.coffee
Fixes inconsistent behavior of CFM menu [#158700996]
- sometimes clicking on an item with a submenu would close the menu rather than opening the submenu
- sometimes clicking on the "anchor" would fail to open or close the menu appropriately
- the original bug was listed as being touch related but in many cases it was more timing-related
- the fix here is to eliminate the timer mechanism for closing the menu in favor of a class-based one
=> Fix inconsistent behavior of CFM menu

src/code/views/share-dialog-view.coffee
- part of recent touch improvements was to set `user-select: none` globally
- the clipboard copy code relies on selection, so it must enable selection locally
- the source linked by comment in the code had already been updated with the fix
=> Fix share dialog copy [#117569803]

src/code/client.coffee
This is used by sagemodeler-site to know when to not display the new/open dialog after the splashscreen.
=> Adds newFileAddsNewToQuery UI option to add #new [#162022225]

src/code/client.coffee, src/code/views/app-view.coffee, src/code/views/share-dialog-view.coffee
- changed post message to post to parent and not top window so that SageModeler (parent) gets message and not docstore iframe (top)
- added optional UI settings for share dialog server url value and label
=> Changes for SageModeler LARA embedding [#162759997]

src/code/client.coffee, src/code/providers/google-drive-provider.coffee, src/code/providers/readonly-provider.coffee
CODAP expects the openedFile event to contain the url in the event metadata.  This was not present when using the event postmessage api.
=> Fix example loads in CODAP [#162641359]

src/code/client.coffee
This fix updates the state metadata before sending file open events.  The listeners to that event used the state to set the autosaves (and to update the top nav)
=> Fixed autosave of files opened via url [#164375620]

src/code/views/modal-view.coffee
Addresses issue logged here: https://www.pivotaltracker.com/story/show/161082471 
When used in Sage, the Open menu would appear halfway off the top of the screen on Firefox, this seems to be related to handling of rendering while the html is in Quirks mode, as the height would be calculated to 0 on Firefox. Changing to VW and VH (Viewport Width and Height) seems to work well on Chrome, Safari, and Firefox on Mac using the all-providers.html test page. 
An alternative approach would be to use the DOCTYPE on the html to enforce strict mode instead of quirks mode, but this would have cascade issues elsewhere (see https://developer.mozilla.org/en-US/docs/Mozilla/Mozilla_quirks_mode_behavior)
=> Change height and width calculations fix Modal Dialogs on Firefox

src/code/providers/google-drive-provider.coffee
This allows sage-modeler-site to specify a resticted list of scopes.
=> Added scropes option to google-drive-provider

src/code/app.coffee
app.clientConnect has an incorrect test whether it is in the root browser window.
This always fails and results in CFM sending postMessage to itself.
=> URL Parameters Processed Twice

src/code/client.coffee
The only difference between the CODAP branch and the master branch is that the code for setting the window title is removed in the CODAP branch. By setting the `appSetsWindowTitle` configuration parameter to true, the desired behavior can be achieved without maintaining a separate CODAP branch.
=> Add `appSetsWindowTitle` configuration parameter to eliminate need for CODAP branch

src/code/providers/provider-interface.coffee
Fixes two bugs:
1. The check for the existing extension was comparing the substring at the end of the name of length extensionLength -1 to the concatenaton of a dot and the extension instead of the substring of extensionLength + 1 (the +1 to add the dot being compared).
2. When the extension was added any existing extension was being dropped with no check to see if the extensions matched.
This change also tries to unpack the dense update code with comments and a conditional path.
=> Fix extension not being added when filename as dot in it [#168903516]

src/code/client.coffee
This will be used to ensure that the `run_remote_endpoint` is set in CODAP when we are wrapped in SageModeler.
CODAP handles `logLaraData` in its version of the LARA provider, and uses it to set the `run_remote_endpoint` using the data LARA passes in.
SageModeler, however, defines a LARA provider but does not handle `logLaraData`. So the only version of `logLaraData` that gets called is the CFM's own client version.
This updates the client code to rebroadcast the message using `_event`. We will then update CODAP to handle this message and set the `run_remote_endpoint` accordingly.
https://www.pivotaltracker.com/story/show/172071393
=> Use _event to broadcast log events to listeners

readme.md
Also a minor tweak to Conversion Notes
[#172226702]
172226702-final-coffeescript-purge
https://www.pivotaltracker.com/story/show/172226702
=> Remove `.coffee` from documentation

src/code/client.js, src/code/providers/s3-provider.test.ts, src/code/providers/s3-provider.ts, src/code/providers/s3-share-provider.test.ts, src/code/providers/s3-share-provider.ts, src/code/utils/config.ts, src/code/utils/s3-share-provider-token-service-helper.test.ts, src/code/utils/s3-share-provider-token-service-helper.ts, src/code/views/share-dialog-view.js
* Loads legacy docstore documents
* fixes 🐞 Revert to shared view doesn't work
* Configure strings using `utils/config.ts`
* Move `s3-share-provider-token-service-helper.ts` to `utils/` directory
* Adds a few more tests around shared loading
[#172324177]
https://www.pivotaltracker.com/story/show/172324177
=> Resolve issues with loading legacy documents

src/code/client.js
https://www.pivotaltracker.com/story/show/173733992
local-file-provider returns `false` from `canOpenSaved`. But it was showing an error during saving as `getOpenSavedParams` was not implemented there. In fact, it doesn't make sense to call `getOpenSavedParams` when `canOpenSaved` returns false, as these params won't be used anyway.
=> Don't require openSavedParams when canOpenSaved is false

src/code/client.js
https://www.pivotaltracker.com/story/show/173733790
The sharing process was:
- assuming that metadata exists and trying to get filename from it
- trying to update `this.state.metadata` after sharing is complete
Comment should explain the fix. I don't really understand where CloudMetadata should be created. It was tempting to create it even in the constructor. But since there are many places where it's created later or the code checks if it's available, it seemed risky before our big CFM update.
=> Fix sharing of documents without filename set

package.json, src/code/providers/s3-provider.ts, src/code/providers/s3-share-provider.ts, src/code/utils/config.ts, src/code/utils/s3-share-provider-token-service-helper.test.ts, src/code/utils/s3-share-provider-token-service-helper.ts
[#173754567]
This PR changes default token-service env to "production" and removes some utilities/helpers/config that were not necessary.
=> Use production token-service, cleanup related files

src/code/utils/translate.js
The goal of this and the other PRs tagged with `[CODAP-sync]` is to attempt to eliminate the differences between the CODAP and master branches. Each PR represents a set of changes that were made on the CODAP branch that seem as though they should be sufficiently general that they can be merged to master and made accessible to all clients. Thus, review should consist of two components:
1. From the CODAP perspective, do the proposed code changes accurately reflect the prior behavior of the CODAP branch?
2. From the non-CODAP perspective, do the proposed code changes make sense as the default behavior for non-CODAP clients as well as for CODAP clients? @ddamelin 
---
[[#172561086]](https://www.pivotaltracker.com/story/show/172561086) Check language of page before language of browser …
=> [CODAP-sync] Check language of page before language of browser

src/code/client.js, src/code/providers/url-provider.js
The goal of this and the other PRs tagged with `[CODAP-sync]` is to attempt to eliminate the differences between the CODAP and master branches. Each PR represents a set of changes that were made on the CODAP branch that seem as though they should be sufficiently general that they can be merged to master and made accessible to all clients. Thus, review should consist of two components:
1. From the CODAP perspective, do the proposed code changes accurately reflect the prior behavior of the CODAP branch?
2. From the non-CODAP perspective, do the proposed code changes make sense as the default behavior for non-CODAP clients as well as for CODAP clients? @ddamelin 
Contains the contents of two commits which reference two PT stories.
--- …
=> [CODAP-sync] Enable CSV import by URL parameter

src/code/utils/lang/de.json, src/code/utils/lang/el.json, src/code/utils/lang/en-US-master.json, src/code/utils/lang/en-US.json, src/code/utils/lang/es.json, src/code/utils/lang/he.json, src/code/utils/lang/nb.json, src/code/utils/lang/nn.json, src/code/utils/lang/tr.json, src/code/utils/lang/zh-TW.json, src/code/views/share-dialog-view.js
PT story provides more detail why it's removed:
https://www.pivotaltracker.com/story/show/173755317
If necessary, we can edit the share URL manually.
I've also removed UI related to launch page that isn't supported anymore.
=> Remove CFMOrigin from LARA share dialog

src/code/providers/s3-provider.ts, src/code/providers/s3-share-provider.ts, src/code/utils/s3-share-provider-token-service-helper.ts
[#173817843]
Previously S3 Share Provider was saving file in the S3 folder using the document name. This doesn't make sense, as when user updates doc name, sharing functionality gets broken. The share link points to the wrong name.
=> Fix a bug making impossible to update shared view after filename update

package.json, src/code/providers/lara-provider.js, src/code/views/share-dialog-view.js
This fixes the bug with linked interactive URLs in the LARA provider using document-server (numeric) ids.
It also fixes a bug with overly complex links being generated by `getShareLink` in `share-dialog-view.js`
For the migration task:
The `new_url` format for the migration of authored interactives is this:
https://<CFM_URL>/autolaunch/autolaunch.html
?documentId=<url-encoded https://models-resources.concord.org/Flegacy-document-store/<LEGACY_ID>>
&server=<CODAP_URL> (we had been including cfmBaseUrl, but I don't think we need to)
&scaling
eg:
```JSON
{
"id": 207249,
"old_url": "https://document-store.concord.org/v2/documents/16046/autolaunch?server=https%3A%2F%2Fcodap.concord.org%2Freleases%2Flatest%2F&buttonText=Launch",
"new_url": …
```
=> Fix linked interactives, LARA Embed URL construction

src/code/providers/lara-provider.js
JQuery was converting JSON documents into multipart form documents, and breaking Rack's upper limit on number of parameter keys.
[#173950259]
=> Fix JQuery JSON PUT request to Docstore on S3 Copy

src/code/views/share-dialog-view.js
The dialog was using encodeURI instead of encodeURIComponent. The encodeURI() function encodes special characters, except: , / ? : @ & = + $ # whereas encodeURIComponent() function encodes special characters and in additional the characters which encodeURI doesn't encode.
=> Fixed shared url encoding in share dialog [#174342352]

src/code/views/menu-bar-view.js
As part of the TypeScript conversion the dropdown anchor reference was broken which caused it not to render which then threw off the styling of the language menu.
CODAP does need to increase their menubar size to give some "breathing space" to the menubar as all the elements (along with the language menu) are butted up on the bottom.  Changing from 24px to 28px here makes it much nicer:
https://github.com/concord-consortium/codap/blob/0aa6c7a9d835a5d6b3f9ca05164ba01dceed8e41/apps/dg/resources/main_page.js#L26
=> Fixed missing dropdown anchor that broke menu styling [#174342649]

build-support/build-opts.js, package-lock.json, package.json, src/assets/index.html
Added version number to index page.
=> Version 1.1.0

src/code/providers/google-drive-provider.js
The v2 api is not returning the correct domain for the download file url making opens fail.  Previously we fell back to changing the domain when the initial domain load failed but a recent change in the behavior of the v2 api causes the error handler not to be called.
=> Changed to always change the Google Drive v2 downfile file location

src/code/utils/translate.js
An earlier merged commit lowercased the language key before filling the translation tables but the language key was not then also lowercased when a translation was looked up causing en-US and zh-TW to fail.
=> Fixed broken language translation

src/code/providers/google-drive-provider.test.ts, src/code/providers/google-drive-provider.ts
[[#178634302]](https://www.pivotaltracker.com/story/show/178634302)
In working through the TypeScript conversion I noticed that the GoogleDriveProvider was loading an instance of the Google Drive API in every function call rather than caching the result of the first load and returning it for all subsequent loads. This PR makes sure we only load the Google Drive API once, in consultation with @dougmartin, and also includes a jest test which in good TDD fashion was written before the fix was implemented.
=> Fix loading of Google Drive API so that we only load it once

src/code/client.test.ts, src/code/client.ts
The good news is that I was able to create an example activity that demonstrates unmodified production CODAP saving/restoring files using attachments. To get it to work, however, one more tweak to provider initialization is required.
=> Fix auto-configuration of InteractiveApiProvider

build-support/build-opts.js, package-lock.json, src/code/client.ts, src/code/providers/interactive-api-provider.test.ts, src/code/providers/interactive-api-provider.ts, src/code/providers/provider-interface.ts
In setting up example activities for testing purposes I realized there was some confusion around wrapping/unwrapping attachment contents that was preventing save/restore of CODAP documents from working correctly.
The following URLs demonstrate the functionality:
CFM Demo saving with attachments:
https://activity-player.concord.org/branch/master/?activity=https%3A%2F%2Fauthoring.staging.concord.org%2Fapi%2Fv1%2Factivities%2F21112.json
CODAP saving without attachments (subject to Firestore 1MB document size limit):
https://activity-player.concord.org/branch/master/?activity=https%3A%2F%2Fauthoring.staging.concord.org%2Fapi%2Fv1%2Factivities%2F21118.json
CODAP saving with attachments:
https://activity-player.concord.org/branch/master/?activity=https%3A%2F%2Fauthoring.staging.concord.org%2Fapi …
=> Working save/restore of CODAP documents as attachments

package.json, src/code/providers/interactive-api-provider.ts
This is essentially an alternative fix for @tejal-shah's bug ([[#172312303]](https://www.pivotaltracker.com/story/show/172312303)). The problem is that the state object communicated between the CFM and its client (CODAP in this case) needs be cloned so that it isn't frozen by the `lara-interactive-api` library. [LARA PR #736](https://github.com/concord-consortium/lara/pull/736) demonstrates what this would look like if we made the library responsible for cloning the state. If we decide not to do so in the library, then this PR demonstrates how it could be done in the client.
=> Fix bug in loading contents of shared CODAP documents via InteractiveApiProvider

package.json, src/code/providers/google-drive-provider.ts, src/code/utils/lang/de.json, src/code/utils/lang/el.json, src/code/utils/lang/en-US-master.json, src/code/utils/lang/en-US.json, src/code/utils/lang/es.json, src/code/utils/lang/he.json, src/code/utils/lang/ja.json, src/code/utils/lang/nb.json, src/code/utils/lang/nn.json, src/code/utils/lang/th.json, src/code/utils/lang/tr.json, src/code/utils/lang/zh-Hans.json, src/code/utils/lang/zh-TW.json
* Also, add message to strings file so it can be localized.
* Updated minor version number
* Tested in CODAP: 
* saved a file to Google Drive, 
* then disabled wireless network, 
* then made a change to the CODAP docuument: saw correct error message.
=> [#177118798] Fix typo in CFM google provider error message

package-lock.json, package.json, src/code/client.ts
[#179610900]
For reasons not entirely understood (yet), recent CFM changes introduced a bug in which the first save of a document to google drive would be invalid, but subsequent saves would be fine. The proximate cause of the bug was that `undefined` was being passed to the `_dialogSave()` function, which had an explicit test of the form `if (stringContent !== null)`. Since in this case the content was `undefined` and not `null`, we proceeded to save the `undefined` content rather than retrieving and saving the actual content.
In the interest of expediency, the fix here is to change the test to `if (stringContent != null)` so that `undefined` and `null` are both handled the same way, i.e. by retrieving and saving the actual content. For general edification and posterity, a little more …
=> Prevent save of undefined content [#179610900]

src/code/client.ts
In the TypeScript conversion some function arguments that had been defaulting to `null` were changed to be optional parameters instead, i.e. `undefined` would be passed instead. In most cases this doesn't matter but in some cases clients are using `===` or `!==` to test specifically for `null`. This PR restores `null` defaults to all function arguments that had them previously.
=> Restore null defaults to some functions arguments that were lost in TypeScript conversion

package-lock.json, package.json, src/code/providers/interactive-api-provider.test.ts, src/code/providers/interactive-api-provider.ts
[[#179611084]](https://www.pivotaltracker.com/story/show/179611084)
Having decided not to implement [LARA PR #736](https://github.com/concord-consortium/lara/pull/736), we instead worked around the interactive API's frozen state in [CFM PR #222](https://github.com/concord-consortium/cloud-file-manager/pull/222) by calling `cloneDeep()` in `getInteractiveState()` and `setInteractiveState()`. Unfortunately, this missed the initial interactive state, a situation that is rectified with this PR.
@scytacki I originally assigned this to Piotr for review, forgetting that he's on vacation. It should be a quick review, however, as it's essentially a trivial follow-up to #222.
=> Call cloneDeep() on initialState

src/code/client.ts
Before this was only waiting on connected which is never send when the CFM is in "wrapper" mode like it is used in SageModeler
=> Changed CFM to wait for either local or iframe connected before opening provider file

src/code/views/select-interactive-state-dialog-view.tsx, src/style/components/select-interactive-state-dialog.styl
This fixes a long standing feature request from Dan - when the smaller linked interactive preview is clicked it is displayed in a larger area but the scaling stayed the same so it was very hard to read.  This also presented a problem during QA so I went ahead and fixed it (and it turned out it was a pretty easy fix)
Existing (unchanged preview selector):
Scaling **BEFORE** Fix
Scaling **AFTER** Fix (this PR)
=> Fixed scaling on linked interactive previews so that it is readable

src/code/client.ts, src/code/providers/google-drive-provider.ts, src/code/views/file-dialog-tab-view.ts
- Relevant story here: https://www.pivotaltracker.com/story/show/179981050
- Version number has not yet updated
- The changes affect providers that authenticate, which I think are only GD and the Document Server provider. I did not test the later, but I believe it is not in use any more. I think, for example, that document sharing is provided through another provider.
- These changes were built off of the then head of the `master` branch. This includes code from PR #231, which have not been included in any CODAP build. Although it is on `master`, I am not sure of its readiness for production nor PR #232 which was merged subsequently. If these are ready for release, I can rebase as appropriate.
=> 179981050 handle gd auth timeout

package-lock.json, package.json, src/code/client.ts, src/code/providers/interactive-api-provider.ts
[[#180401986]](https://www.pivotaltracker.com/story/show/180401986)
CODAP presents the splash screen but makes decisions about when to show/hide it based on event notifications from CFM. In this particular instance, CFM needs to show a dialog itself with which the CODAP splash screen interferes. Therefore, CFM sends the new `requiresUserInteraction` message when it needs to present a dialog during startup and in a separate [CODAP PR](https://github.com/concord-consortium/codap/pull/398), CODAP responds by hiding the splash screen when the CFM requires user interaction.
Also, increment the version number, fix a typo, and run `npm audit fix` while we're in the neighborhood.
=> Send `requiresUserInteraction` event when putting up state selection dialog

src/code/client.test.ts, src/code/client.ts, src/code/providers/test-provider.ts
This adds a early exit on saves if the hash of the content doesn't change between the first load and save or between commanded saves.
This also adds a test provider so that we can use jest tests to test the new code that was added.
The "saved" flag was being set on the load event instead of the dirty flag.  The update is to set the dirty flag to true if the content requires conversion.
=> Added save hash check and fixed incorrect saved flag setting on file loads [#180438651]

src/style/mixins/icons.styl
Caused by the TypeScript conversion?
This fixes the CodapIvy font path which is used in the file dialogs.  This is what it looked like before the fix:
and this is after the fix:
=> Fix relative path of fonts

build-support/build-opts.js
There was a recent adjustment to font paths for the Codap-Ivy icon font. Apparently this was to fix an error in the Sage build. It broke the references in the CODAP build. As far as I know, the only symbols actually used in the CODAP build are for file list icons in the Open/Save/... dialogs. Fixed the scripts for the CODAP build to restore the original paths.
=> [#180892247] Fix bug: icon font path broken for CODAP Build.

src/code/client.ts
This changes the code to use the newish rename method on the CloudMetadata class which handles setting the filename extension automatically.
=> Fix loss of file extension on rename after copy [#174494057]

src/code/client.test.ts, src/code/client.ts
This fix is really for testing so that alternate cfm branches spec'ed in the query string are included in the copied tab.
=> Save query string on copy [#174494057]

src/code/client.ts
Before this fix the autosave was short-circuited if the document wasn't dirty, now it always saves.
This fixes a bug where if the user changed the language more than once the original document wasn't saved the second time because it wasn't dirty after the first language change save.
=> Fix autosave on language change [#175390295]

src/code/client.ts
Before this change when an example file was loaded and then the language was changed a save dialog would be shown as the readonly provider can't save but there were other providers that could, eg Google Drive.
With this change the current provider saves only if it can, otherwise it falls back to saving a temp file in local storage.
=> Remove autosave of readonly providers in language switching [#175390295]

package-lock.json, package.json, src/code/client.ts, src/code/providers/interactive-api-provider.ts, src/code/providers/provider-interface.ts
This adds an `onUnload` callback that is triggered when Lara interactive API clients request the final interactive state when unloading from the page.  The initial use for this will be to get the final SageModeler/CODAP state from an interactive.
=> Added onUnload callback [#181169438]

src/code/providers/interactive-api-provider.ts
Some interactives, like the full-screen wrapper always report they are in runtime  mode, even when loaded in a report which does not define the interactive member.  This change makes the interactive member of the message optional.
=> Change interactive member of init message optional [#181103123]

src/code/providers/interactive-api-provider.ts
Some interactives, like the full-screen wrapper always report they are in runtime  mode, even when loaded in a report which does not define the interactive member.  This change makes the interactive member of the message optional.
*NOTE*: this is a redo of the branch used in this PR: https://github.com/concord-consortium/cloud-file-manager/pull/261/files.  It was merged into another PR branch but GitHub didn't change the base branch when the other branch was merged.
=> Change interactive member of init message optional [#181103123] (Redo of PR #261 due to bad merge)

src/code/app-options.ts, src/code/client.test.ts, src/code/client.ts, src/code/providers/interactive-api-provider.ts
The commit does three things:
1. This removes the old content hash check which was buggy, along with the save options that had to be drilled down.
2. Adds a contentSaveFilter callback.  This is used by SageModeler to pin the various version numbers in the content, thus avoiding saves when the content itself doesn't change.  This is needed so that linked interactives don't get their modified time updated when the content itself doesn't change.
3. Fixes a bug found when saving the interactive state for attachments..
=> Adds check for contentSaveFilter option before saving the content [#181175814]

src/code/client.ts
Prior to this fix if the user navigated away from the page while the linked interactive choice dialog was shown the autosave dialog would be triggered.  The dialog was shown as the provider is not set in the metadata until the linked choice dialog is closed.
This also fixes a yet to be used (and maybe never to be used) resolve of the interactive state when not unloading.  Previous an empty object was returned but `undefined` should have been used to not that no update of the state is needed.
=> Fixed auto save provider incorrectly showing [#182038658]

package-lock.json, package.json, src/assets/examples/all-providers.html, src/code/app-options.ts, src/code/providers/interactive-api-provider.test.ts, src/code/providers/interactive-api-provider.ts, src/code/views/app-view.tsx
Also added `iframeAllow` client option so that SageModeler (and other apps that use CFMs wrapper) to inject `bluetooth` and other allowed features into the outer app iframe.
=> Added rewrite of sensor-interactive domain in interactive state links [#182916725]

.travis.yml, src/code/providers/interactive-api-provider.test.ts, src/code/providers/interactive-api-provider.ts
This fixes a bug, surfaced via the StoryQ CODAP plugin, where a large initial interactive state in a shared document was loaded and then saved on startup, bypassing the attachment checking in the save method.
This also fixes an error, found during this fix, of the attachment state being leaked out of the save call via the callback.  It should instead return the actual saved state in that case, not the attachment wrapper.
=> Moved attachment creation to inside setInteractiveState [#183681726]

src/code/providers/interactive-api-provider.test.ts, src/code/providers/interactive-api-provider.ts
Before this change if a student shared a Sage interactive which was displaying linked state instead of that question's interactive state (as the student had not made changes yet) the sharing plugin would show an empty document instead of the linked state seen by the student.  The sharing plugin uses the portal-report which uses the report initInteractive message which does not send linked interactive states as part of its message (only the runtime message does).  By autosaving the directly linked state when there is no current state the sharing plugin will now mirror what the student sees.
=> Added autosaving of directly linked state when there is no current state [#183903716]

src/code/providers/google-drive-provider.ts
Between v2 and v3 the client method changed from patch to update and the parameter changed from title to name.
=> Fixed renaming with Google Drive provider [#183722341]

src/code/views/share-dialog-tabs-view.test.tsx, src/code/views/share-dialog-tabs-view.tsx, src/code/views/share-dialog-view.test.tsx, src/code/views/share-dialog-view.tsx, src/code/views/share-loading-view.tsx, src/style/components/share-loading-view.styl
Also fixed long standing css issues with the share loading dialog:
1. Set svg loading spinner size to 16px x 16px
2. Centered the spinner and text both horizontally and vertically in dialog
=> Removed LARA tab from sharing dialog [#184184524]

src/code/client.ts, src/code/providers/google-drive-provider.ts, src/code/providers/provider-interface.ts
The new Google auth flow requires a popup to show for authorization before auto opening a file using the url parameters.
=> Added forced authorization when opening Google Drive files from url param [#184053851]

src/code/views/file-dialog-tab-view.ts
This allows the user to export a png or svg from CODAP with the same name as the CODAP document.
=> Added check of extension of saves [#143693677]

src/code/views/file-dialog-tab-view.ts
The logic should have been: is this the initial folder or has the provider changed and instead it was is this the initial folder and has the provider changed.
=> Fixed blank parent folder when showing open dialog the second time [#184192561]

src/code/client.test.ts, src/code/client.ts, src/code/providers/provider-interface.ts
Instead of showing a save error on readonly shared Google drive files the save dialog is always shown on saves.
=> Added better read-only support [#180756824]

src/code/views/file-dialog-tab-view.ts
This also adds a "Loading..." message which was found to be needed for large file lists.
=> Fixed double click of top level Google drive list [#184360746]

src/code/views/file-dialog-tab-view.ts
This prevented a file opened in the readonly provider from being saved in the google provider
=> fix: :bug: Removed changed client provider check in file dialog tab

src/code/views/local-file-tab-save-view.ts
This fixes a recent change made when adding extensions to the export dialog.  The export dialog still has the extension but the local file save no longer does (as requested).
=> Remove extension from local file save [#184486444]

src/code/providers/google-drive-provider.ts, src/code/views/confirm-dialog-view.ts, src/style/components/confirm-dialog.styl
This should cause the browser popup blocker to not block the popup as it is handled via a user gesture
=> Added alert popup when Google file parameter is detected [#184485563]

src/code/app-options.ts, src/code/client.test.ts, src/code/client.ts
This will allow SageModeler to rewrite the iframe title that was broken with the early Korean translations.
=> feat: Added content load filter [PT-185485076]

src/code/providers/google-drive-provider.ts
Automatically setting the query obscures the folders.
=> fix: Remove search query on Google picker file opens

.eslintrc, readme.md, src/code/app-options.ts, src/code/client.ts, src/code/providers/document-store-provider.ts, src/code/providers/interactive-api-provider.ts, src/code/providers/lara-provider.ts, src/code/providers/provider-interface.ts, src/code/providers/url-provider.test.ts, src/code/ui.ts, src/code/utils/translate.ts, src/code/views/app-view.tsx, src/code/views/modal-dialog-view.tsx, src/code/views/modal-view.tsx, src/code/views/select-interactive-state-dialog-view.tsx, src/code/views/share-dialog-status-view.tsx, src/code/views/share-dialog-tabs-view.tsx, src/code/views/share-dialog-view.tsx
This started with the simple task of updating the ReadMe with information about the new `@concord-consortium/cloud-file-manager` library option.
- While at it I decided to add some information about the options that could be passed to the CFM in the ReadMe as well.
- While doing that it seemed like some additional comments about the meaning of some of the options was warranted, although I bailed out before documenting all of them.
- Finally, while looking at the definitions of the various options I was struck by the number of semicolons in this supposedly semicolon-less project and updated the ESLint configuration to make things more consistent.
=> chore: update comments and ReadMe; eliminate more semicolons for consistency

package-lock.json, package.json
This is a hotfix off the 1.9.0 release and not master that removes the change user link in the Google Dialog.  That link causes more scopes to be requested than required.
=> Version 1.9.1

src/code/app-options.ts, src/code/client.test.ts, src/code/client.ts, src/code/providers/provider-interface.ts, src/code/ui.ts, src/code/views/app-view.tsx, src/style/app.styl, src/style/mixins/default.styl
The goal here, as with other recent PRs, is to enable/improve support for clients such as CODAP v3 to load the CFM as an npm library while not changing the behavior of the CFM for existing clients such as CODAP v2 and Sage Modeler.
- New configuration option `isClientContent`
- Previously, CFM assumed that client content had a top-level `metadata` property. This assumption is preserved for backward-compatibility, but now clients can specify a custom function for identifying client content. CODAP v3 uses this to pass a custom function that can recognize CODAP v2 or v3 documents.
- Fix `ProviderInterface.getClientContent` so that it respects the `wrapFileContent` setting.
- The `getClientContent` function is one side of a coin with the `getContent` function on the other side.
- The …
=> feat: improve ability to import as npm library (support CODAP v3)

package-lock.json, package.json, src/style/components/tabbed-panel.styl, src/style/mixins/components.styl
- add missing `px` to inadvertently dimensionless values
- specify `line-height normal` for `modal-button` so it doesn't default to something else in CODAP v3
- bump version to 2.0.0-pre.2
=> fix: style fixes/tweaks for npm library

bin/build-library.sh, package-lock.json, package.json
The CFM code contains the string `__PACKAGE_VERSION__` in several places. The expectation is that this string will be replaced by the actual CFM version number from `package.json` at build time. For the webpack build, this is handled by the `ReplaceInFileWebpackPlugin`. For the library export we don't have a bundler that can handle the string replacement. Therefore, this PR introduces the `build-library.sh` bash script which builds the exported library folders with calls to `tsc`, as before, then also uses `grep` and `sed` to perform the string replacement of the version number. The script was developed with the help of ChatGPT.
=> fix: export CFM version number rather than `__PACKAGE_VERSION__`

package-lock.json, package.json, src/code/views/share-dialog-view.tsx
The `ShareDialogView` is responsible for displaying the various sharing urls, embedding urls, etc. that result from sharing a document. It constructs these urls from constituent parts passed into it as props, e.g. `sharedDocumentId` and `sharedDocumentUrl`. Utility methods in the form of `getShareUrl()`, `getShareLink()`, and `getEmbed()` construct these urls from the provided props. These urls are _also_ stored in state through an asynchronous mechanism that is triggered by the user pressing the `Enable Sharing` button. These state variables are set to the return values of the `getShareLink()` and `getEmbed()` utility methods, which construct them from props, as previously stated. The bug occurs because in v3, the setState callback occurs before the props have been updated, so the state …
=> fix: blank share url in share dialog [PT-188104620]

package-lock.json, package.json, readme.md, src/code/app-options.ts, src/code/client.ts, src/code/ui.ts, src/code/utils/translate.ts, src/code/views/app-view.tsx, src/code/views/menu-bar-view.ts
CODAP v2 required a full page reload to switch language due to SproutCore. CODAP v3 will support dynamic language switching without a page reload, so the CFM needs to as well. With this PR, CFM supports the notion of current language rather than just a default language set on startup. The translation function and the rendering of the menus respect the current language. Since the File menu is provided by the client, there's a new API for replacing the existing menu.
=> feat: support dynamic language switching

.npmrc, package.json
"engineStrict" in 'package.json' is deprecated, see https://github.com/concord-consortium/codap/pull/786#pullrequestreview-1414210977
=> chore(npm): Add 'engine-strict' to project config (PT-185071892)

package-lock.json, package.json, src/assets/examples/no-frame.html, src/code/client.ts, src/code/utils/config.ts, webpack.config.js
This fixes a bug when sharing plain text content.
It also fixes a bug that was breaking all sharing in these examples because the sharing provider uses at `process.env`.
The `process.env` reference still exists in the library, so any application using the CFM library needs to handle this reference on its own.
TODO:
=> add share button to no-frame example

package-lock.json, package.json, src/code/app-options.ts, src/code/views/menu-bar-view.ts, src/style/components/menu-bar.styl
[[CODAP-801](https://concord-consortium.atlassian.net/browse/CODAP-801)] Move Settings and Help buttons from Tool shelf to CFM header
- Support other client-provided menus in the CFM toolbar
- Make the CODAP logo in the CFM toolbar clickable
- update version to `2.1.0-pre.5` (for testing)
Note that the `Dropdown` component used for menus in the CFM has some undesirable behaviors like not closing menus when the escape key is pressed or the user clicks outside the menu, making it possible to show multiple CFM menus at the same time. I made no effort to fix these issues at this time, although we may (or may not) want to for the beta.
[CODAP-801]: https://concord-consortium.atlassian.net/browse/CODAP-801?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1ci …
=> [CODAP-801] Support other client-provided menus in the CFM toolbar

package-lock.json, package.json, src/code/views/dropdown-view.ts, src/style/components/dropdown-menu.styl, src/style/components/menu-bar.styl
[[CODAP-817](https://concord-consortium.atlassian.net/browse/CODAP-817)] CFM menu issues -- styling, closing
Several issues with CFM menus that may be worth fixing for the beta:
- asymmetric padding on Help/Settings menu button labels
- insufficient space between menu item icons and labels
- can open multiple CFM menus simultaneously
- escape key should close menus
Testable at https://codap3.concord.org/branch/cfm-menu-issues/.
[CODAP-817]: https://concord-consortium.atlassian.net/browse/CODAP-817?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: styling and closing issues with CFM menus

cypress/support/elements/CfmObject.js, package-lock.json, package.json, src/code/views/share-dialog-status-view.test.tsx, src/code/views/share-dialog-status-view.tsx, src/code/views/share-dialog-tabs-view.test.tsx, src/code/views/share-dialog-tabs-view.tsx, src/code/views/share-dialog-view.test.tsx, src/style/components/share-dialog.styl
Jira story: https://concord-consortium.atlassian.net/browse/CODAP-860
This story improves the styling for the share modal:
- The button for copying a share url is now an actual button that looks like other buttons and is repositioned.
- The preview shared view button is now an actual button and looks like other buttons.
- The stop sharing button looks like other buttons now and has been repositioned.
- The Embed text area now has a border like an input field.
Most of these features can be seen in the attached screenshot.
=> Codap-860 Restyle Copy Button
